mysql:
  url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: q002526

eureka:
  instance: localhost
  port: 8011
